name: SIT Build

on:
    push:
        paths-ignore:
        - '.github/*'
        - '.github/*_TEMPLATE/**'
        - '*.md'
    pull_request:
        paths-ignore:
        - '.github/*'
        - '.github/*_TEMPLATE/**'
        - '*.md'

jobs:
  
  build:

    strategy:
      matrix:
        configuration: [Release, Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to

    env:
      SolutionName: StayInTarkov                              
      CSProj: Source/StayInTarkov.csproj               

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0


    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore all projects
    - name: dotnet Restore
      run: dotnet restore

    # Publish the Launcher as Self-Contained Single-File
    - name: dotnet Publish
      run: |
        mkdir ${{ env.SolutionName }}-${{ matrix.configuration }}
        dotnet build ${{ env.CSProj }} -c ${{ matrix.configuration }} -o ${{ env.SolutionName }}-${{ matrix.configuration }}

    - name: Remove unnecessary files
      run: |
          del ${{ env.SolutionName }}-${{ matrix.configuration }}\StayInTarkov.pdb
          del ${{ env.SolutionName }}-${{ matrix.configuration }}\PresentationFramework.xml
          del ${{ env.SolutionName }}-${{ matrix.configuration }}\PresentationFramework.dll
          del ${{ env.SolutionName }}-${{ matrix.configuration }}\Newtonsoft.Json.dll



    # Upload artifact unless its merge to master
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: StayInTarkov-Build-${{ matrix.configuration }}
        path: ${{ env.SolutionName }}-${{ matrix.configuration }}\
        if-no-files-found: error
    

    - name: Set build date
      run: echo "BUILD_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    # Create release from the compressed file if pushed to master
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
      with:
        draft: true
        generate_release_notes: true
        files: ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
        tag_name: StayInTarkov.Client-v1.${{ github.run_number }}
